### ISSUE TITLE
multiple memes in single request possible?

### ISSUE THREAD

**Issue by narayanansampath** [R3l3ntl3ss/Meme_Api#20]
Can I get multiple memes with a single api request as it takes lot of time to call the api repeatedly and store the links

**Comment by R3l3ntl3ss** [comment]
Hey Narayanan
I have added two endpoints to get multiple memes by specifying the count, in the latest commits. 
You could either use `/gimme/<count>` or `/gimme/<subreddit>/<count>` to get a custom number of memes. I hope this was able to solve your problem.

If you have any more suggestions feel free to let me know.

**Comment by narayanansampath** [comment]
> Hey Narayanan
> I have added two endpoints to get multiple memes by specifying the count, in the latest commits.
> You could either use `/gimme/<count>` or `/gimme/<subreddit>/<count>` to get a custom number of memes. I hope this was able to solve your problem.
> 
> If you have any more suggestions feel free to let me know.

Thank you very much. Also what is the maximum number of data in single response?

**Comment by R3l3ntl3ss** [comment]
You could request upto 100 in a single request. But if you are going to request a lot within a short period of time then you will find some memes to be repeating, as new memes wouldn't have been added within that time.
