### ISSUE TITLE
API is unreachable, Heroku application error

### ISSUE THREAD

**Issue by xnstad** [R3l3ntl3ss/Meme_Api#48]
API is not working as of today, been slow these last few days. Too many requests or service outage maybe?

**Comment by R3l3ntl3ss** [comment]
Hey @xnstad , sorry for the late response. 

When I created this API I didn't think it would be used by anyone else but me. So it was not designed to handle the load that it is currently facing. I have come to realize that a lot of people are using the API and so I decided to rewrite it from scratch. 
In the latest version, I have added cache support so your requests will be handled much faster than before and it should be way more stable than before.

If you have any suggestions feel free to let me know. Thanks a lot for using my API.
