### ISSUE TITLE
Spoiler bool

### ISSUE THREAD

**Issue by No-Death** [R3l3ntl3ss/Meme_Api#52]
Is it possible for you to add a spoiler boolean? If the meme/picture is a spoiler it should be set to True. Would be nice, or if theres a way for me to check that already?

**Comment by R3l3ntl3ss** [comment]
Hey @No-Death 
Sorry for the late response. I have added a Spoiler tag for every post in the last commit. You can get the spoiler boolean directly from the response now. Hope this helps.
