### ISSUE TITLE
How do i get only the url to the meme?

### ISSUE THREAD

**Issue by Los-3r** [R3l3ntl3ss/Meme_Api#55]
im trying to make an app where you can easily get memes, and i need only the url for the image of the meme. how do i do this?

**Comment by R3l3ntl3ss** [comment]
Hey,

The response is in the form of JSON so you can just use the `url` key to get the value.

**Comment by Los-3r** [comment]
how? do i just put something like https://meme-api.herokuapp.com/gimme/memes/1/url ?

**Comment by R3l3ntl3ss** [comment]
Nope, it has to be done on your code. What language are using?

**Comment by R3l3ntl3ss** [comment]
This is how would do it in python.

```python
import requests

response = requests.get("https://meme-api.herokuapp.com/gimme/memes").json()

print(response["url"])
```

**Comment by 3top1a** [comment]
Just spent like 2 hours making a regex. F

`urls = (re.findall('https://i.redd.it/.*.[jpg|png]\"', html))`
